# A task file that install the toolings. 
# 1. task --list
# 2. task <SPECIFY_TASK>

# https://taskfile.dev

version: '3'

silent: true

tasks:
  brew:
    desc: Installs brew
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  terraform:
    desc: installs Terraform
    deps:
      # dependencies
      - task: brew
    cmds:
      - brew install terraform

  git:
    desc: installs git
    deps:
      - brew
    cmds:
      # sequentially executed dependencies
      - brew install git 

  kubectl:
    desc: Installs kubectl
    deps:
      - brew
    cmds:
      - brew install kubectl
      
  python3:
    desc: Installs python3
    deps:
      - brew
    cmds:
      - brew install python3
